name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, window-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20'
      - name: Install dependcies
        run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8 app.py